# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f126e189db0afd2ddea7270ecef6706864bd24d61c9bd00f37bc82568e1af568d10d275b6a763df271f26a7e99ad0264fe55579739daf77616cd131e39771c66

test:
  secret_key_base: c5d36a6ed08577fc302574fc4eb0be192013009ce9586ca1cbd32adb87422e48f545c9616fae08f4ec3cfae737d084d39eab7ee7f478033041bccc54d591fc11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
